---
# Ansible playbook related variables
HOME: "{{ lookup('env', 'HOME') }}"
NAMESPACE: metal3
CRS_PATH: "{{ metal3_dir }}/vm-setup/roles/v1aX_integration_test/templates"
TEMP_GEN_DIR: "{{ metal3_dir }}/vm-setup/roles/v1aX_integration_test/files/manifests"
MANIFESTS_DIR: "{{ metal3_dir }}/vm-setup/roles/v1aX_integration_test/files"
EPHEMERAL_CLUSTER: "{{ lookup('env', 'EPHEMERAL_CLUSTER') | default('kind') }}"
CLUSTERCTL_PATH: "{{ HOME }}/go/src/github.com/metal3-io/cluster-api/bin"
CLUSTER_APIENDPOINT_HOST: "{{ lookup('env', 'CLUSTER_APIENDPOINT_HOST') }}"
API_ENDPOINT_PORT: "{{ lookup('env', 'API_ENDPOINT_PORT') | default(6443, true) }}"
CLUSTER_APIENDPOINT_IP: "{{ lookup('env', 'CLUSTER_APIENDPOINT_IP') }}"
CLUSTER_NAME: "{{ lookup('env', 'CLUSTER_NAME') | default('test1', true) }}"
NUM_OF_MASTER_REPLICAS: "{{ lookup('env', 'NUM_OF_MASTER_REPLICAS') | default(1, true) }}"
NUM_OF_WORKER_REPLICAS: "{{ lookup('env', 'NUM_OF_WORKER_REPLICAS') | default(1, true) }}"
NUM_NODES: "{{ lookup('env', 'NUM_NODES') | default(2, true) }}"
KUBECONFIG_PATH: "/home/ubuntu/.kube/config"
KUBERNETES_VERSION: "{{ lookup('env', 'KUBERNETES_VERSION') | default('v1.18.0', true) }}"

KUBERNETES_BINARIES_VERSION: "{{ lookup('env', 'KUBERNETES_BINARIES_VERSION') | default(lookup('env', 'KUBERNETES_VERSION') | default('v1.18.0', true), true) }}"
KUBERNETES_BINARIES_CONFIG_VERSION: "{{ lookup('env', 'KUBERNETES_BINARIES_CONFIG_VERSION') | default('v0.2.7', true) }}"

IP_STACK: "{{ lookup('env', 'IP_STACK') | default('v4', true) }}"
PROVISIONING_POOL_RANGE_START: "{{ lookup('env', 'PROVISIONING_POOL_RANGE_START') | default('172.22.0.100', true) }}"
PROVISIONING_POOL_RANGE_END: "{{ lookup('env', 'PROVISIONING_POOL_RANGE_END') | default('172.22.0.200', true) }}"
PROVISIONING_CIDR: "{{ lookup('env', 'PROVISIONING_CIDR') | default('24', true) }}"
BAREMETALV4_POOL_RANGE_START: "{{ lookup('env', 'BAREMETALV4_POOL_RANGE_START') | default('192.168.111.100', true) }}"
BAREMETALV4_POOL_RANGE_END: "{{ lookup('env', 'BAREMETALV4_POOL_RANGE_END') | default('192.168.111.200', true) }}"
EXTERNAL_SUBNET_V4_PREFIX: "{{ lookup('env', 'EXTERNAL_SUBNET_V4_PREFIX') | default('24', true) }}"
EXTERNAL_SUBNET_V4_HOST: "{{ lookup('env', 'EXTERNAL_SUBNET_V4_HOST') | default('192.168.111.1', true) }}"
BAREMETALV6_POOL_RANGE_START: "{{ lookup('env', 'BAREMETALV6_POOL_RANGE_START') | default('fd55::100', true) }}"
BAREMETALV6_POOL_RANGE_END: "{{ lookup('env', 'BAREMETALV6_POOL_RANGE_END') | default('fd55::200', true) }}"
EXTERNAL_SUBNET_V6_PREFIX: "{{ lookup('env', 'EXTERNAL_SUBNET_V6_PREFIX') | default('64', true) }}"
EXTERNAL_SUBNET_V6_HOST: "{{ lookup('env', 'EXTERNAL_SUBNET_V6_HOST') | default('fd55::1', true) }}"
IRONIC_HOST_IP: "{{ lookup('env', 'IRONIC_HOST_IP') | default('172.22.0.2', true) }}"
DEPLOY_KERNEL_URL: "{{ lookup('env', 'DEPLOY_KERNEL_URL') }}"
DEPLOY_RAMDISK_URL: "{{ lookup('env', 'DEPLOY_RAMDISK_URL') }}"
IRONIC_AUTH_STRATEGY: "{{ lookup('env', 'IRONIC_AUTH_STRATEGY') | default('noauth', true) }}"
IRONIC_URL: "{{ lookup('env', 'IRONIC_URL') }}"
IRONIC_INSPECTOR_URL: "{{ lookup('env', 'IRONIC_INSPECTOR_URL') }}"
POD_CIDR: "{{ lookup('env', 'POD_CIDR') }}"
SERVICE_CIDR: "10.96.0.0/12"
CAPM3RELEASE: "{{ lookup('env', 'CAPM3RELEASE') | default('v0.3.1', true) }}"
CAPIRELEASE: "{{ lookup('env', 'CAPIRELEASE') | default('v0.3.0', true) }}"
SSH_PRIVATE_KEY: "{{ lookup('env', 'SSH_KEY') }}"
SSH_PUB_KEY_CONTENT: "{{ lookup('file', '{{ HOME }}/.ssh/id_rsa.pub') }}"
IMAGE_USERNAME: "{{ lookup('env', 'IMAGE_USERNAME') | default('metal3', true)}}"

# Environment variables for deployment. IMAGE_OS can be Centos or Ubuntu, change accordingly to your needs.
IMAGE_OS: "{{ lookup('env', 'IMAGE_OS') | default('Centos', true)}}"
CONTAINER_RUNTIME: "{{ lookup('env', 'CONTAINER_RUNTIME') | default('podman', true)}}"
DEFAULT_HOSTS_MEMORY: "{{ lookup('env', 'DEFAULT_HOSTS_MEMORY') | default('4096', true)}}"
CAPI_VERSION: "{{ lookup('env', 'CAPI_VERSION') | default('v1alpha3', true)}}"
CAPM3_VERSION: "{{ lookup('env', 'CAPM3_VERSION') | default('v1alpha3', true)}}"
IRONIC_IMAGE_DIR: "{{ lookup('env', 'IRONIC_IMAGE_DIR') | default('/opt/metal3-dev-env/ironic/html/images')}}"
IRONIC_ENDPOINT_BRIDGE: "{{ lookup('env', 'CLUSTER_PROVISIONING_INTERFACE') | default('provisioning')}}"

# Distibution specific environment variables
IMAGE_NAME: "{{ lookup('env', 'IMAGE_NAME') | default('bionic-server-cloudimg-amd64.img', true)}}"
RAW_IMAGE_NAME: "{{ lookup('env', 'IMAGE_RAW_NAME') | default('bionic-server-cloudimg-amd64-raw.img', true)}}"
IMAGE_LOCATION: 'https://cloud-images.ubuntu.com/bionic/current'
IMAGE_URL: "http://172.22.0.1/images/{{ RAW_IMAGE_NAME }}"
IMAGE_CHECKSUM: "http://172.22.0.1/images/{{ RAW_IMAGE_NAME }}.md5sum"

IMAGE_NAME_CENTOS: "{{ lookup('env', 'IMAGE_NAME') | default('CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64.qcow2', true)}}"
RAW_IMAGE_NAME_CENTOS: "{{ lookup('env', 'IMAGE_RAW_NAME') | default('CentOS-8-GenericCloud-8.1.1911-20200113.3.x86_64-raw.img', true)}}"
IMAGE_LOCATION_CENTOS: 'https://cloud.centos.org/centos/8/x86_64/images'
IMAGE_URL_CENTOS: "http://172.22.0.1/images/{{ RAW_IMAGE_NAME_CENTOS }}"
IMAGE_CHECKSUM_CENTOS: "http://172.22.0.1/images/{{ RAW_IMAGE_NAME_CENTOS }}.md5sum"

provision_cluster_actions:
    - "ci_test"
    - "provision_cluster"
    - "feature_test_provisioning"
provision_controlplane_actions:
    - "ci_test"
    - "provision_controlplane"
    - "feature_test_provisioning"
provision_workers_actions:
    - "ci_test"
    - "provision_worker"
    - "feature_test_provisioning"
deprovision_cluster_actions:
    - "ci_test"
    - "deprovision_cluster"
    - "feature_test_deprovisioning"
deprovision_controlplane_actions:
    - "ci_test"
    - "deprovision_controlplane"
    - "feature_test_deprovisioning"
deprovision_workers_actions:
    - "ci_test"
    - "deprovision_worker"
    - "feature_test_deprovisioning"
verify_actions:
    - "ci_test"
    - "feature_test_provisioning"
    - "pivoting"
cleanup_actions:
    - "ci_test"
    - "feature_test_deprovisioning"
image_download_actions:
    - "ci_test"
    - "provision_controlplane"
    - "provision_worker"
