packages:
  ubuntu:
    common:
      packages:
        - curl
        - dnsmasq
        - nmap
        - ovmf
        - patch
        - psmisc
        - wget
        - libvirt-clients
        - libvirt-dev
        - bridge-utils
        - jq
        - unzip
        - yarn
        - genisoimage
        - qemu-kvm
        - libguestfs-tools
        - gir1.2-polkit-1.0
        - libpolkit-agent-1-0
        - libpolkit-gobject-1-0
    bionic:
      packages:
        - libvirt-bin
        - libpolkit-backend-1-0
    focal:
      packages:
        - libvirt-daemon
        - libvirt-daemon-system
    pip3:
     - virtualbmc
     - lxml
     - netaddr
     - libvirt-python
     - six
     - docker-py
  centos:
    rhel7:
        packages:
         - curl
         - dnsmasq
         - NetworkManager
         - nmap
         - OVMF
         - patch
         - psmisc
         - vim-enhanced
         - wget
         - ansible
         - bind-utils
         - jq
         - libguestfs-tools
         - redhat-lsb-core
         - unzip
         - genisoimage
         - qemu-kvm
         - libvirt
         - libvirt-devel
         - libvirt-daemon-kvm
         - libvirt-python
         - libguestfs-tools
         - python-lxml
         - polkit-pkla-compat
         - python-netaddr
         - virt-install
         - python-six
    rhel8:
        packages:
         - curl
         - dnsmasq
         - edk2-ovmf
         - NetworkManager
         - nmap
         - patch
         - psmisc
         - vim-enhanced
         - wget
         - ansible
         - bind-utils
         - jq
         - libguestfs-tools
         - redhat-lsb-core
         - unzip
         - genisoimage
         - qemu-kvm
         - libvirt
         - libvirt-devel
         - libvirt-daemon-kvm
         - python3-libvirt
         - libguestfs-tools
         - python3-lxml
         - polkit-pkla-compat
         - python3-netaddr
         - virt-install
         - network-scripts
         - firewalld
         - python3-six
