---
  - name: Create a temporary manifest directory if it does not exist
    file:
      path: "{{ TEMP_GEN_DIR }}"
      state: directory
      mode: '0755'

  - name: Generate clusterctl env file
    template:
      src: "{{ CRS_PATH }}/clusterctl_env_template_{{ IMAGE_OS|lower }}.rc"
      dest: "{{ TEMP_GEN_DIR }}/clusterctl_env_{{ IMAGE_OS|lower }}.rc"

  - name: Generate clusterctl cluster template
    template:
      src: "{{ CRS_PATH }}/cluster-template-{{ item }}.yaml"
      dest: "{{ HOME }}/.cluster-api/overrides/infrastructure-metal3/{{ CAPM3RELEASE }}/cluster-template-{{ item }}.yaml"
    with_items:
      - cluster
      - controlplane
      - workers

  - name: Generate templates
    shell: >
      . {{ TEMP_GEN_DIR }}/clusterctl_env_{{ IMAGE_OS|lower }}.rc &&
      {{ CLUSTERCTL_PATH }}/clusterctl config cluster {{ CLUSTER_NAME }}
      --from {{ HOME }}/.cluster-api/overrides/infrastructure-metal3/{{ CAPM3RELEASE }}/cluster-template-{{ item }}.yaml
      --kubernetes-version {{ KUBERNETES_VERSION }}
      --control-plane-machine-count={{ NUM_OF_MASTER_REPLICAS }}
      --worker-machine-count={{ NUM_OF_WORKER_REPLICAS }}
      --target-namespace={{ NAMESPACE }} > {{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_{{ item }}_{{ IMAGE_OS|lower }}.yaml
    with_items:
      - cluster
      - controlplane
      - workers
